// Product names and concepts from NAM5AN/malang; all 3D material tuning is new.
export const textures = {
  jelly: {
    label: "촉촉한 젤리",
    compliance: 0.0007,
    drag: 3.4,
    stretch: 1.9,
    roughness: 0.19,
    transmission: 0.56,
  },
  liquid: {
    label: "흐르는 젤리",
    compliance: 0.0016,
    drag: 4,
    stretch: 2.15,
    roughness: 0.12,
    transmission: 0.78,
  },
  foam: {
    label: "폭신한 크림",
    compliance: 0.001,
    drag: 8,
    stretch: 1.8,
    roughness: 0.65,
    transmission: 0.04,
  },
  crunch: {
    label: "오독오독 비즈",
    compliance: 0.00045,
    drag: 4.5,
    stretch: 1.7,
    roughness: 0.32,
    transmission: 0.27,
  },
  rubber: {
    label: "쫀득한 탄력",
    compliance: 0.00014,
    drag: 1.9,
    stretch: 1.7,
    roughness: 0.2,
    transmission: 0.25,
  },
  squishy: {
    label: "천천히 복원",
    compliance: 0.0024,
    drag: 28,
    stretch: 1.8,
    recovery: 2.8,
    roughness: 0.5,
    transmission: 0.09,
  },
  cotton: {
    label: "몽실한 솜",
    compliance: 0.003,
    drag: 24,
    stretch: 1.7,
    recovery: 3.8,
    roughness: 0.92,
    transmission: 0,
  },
  clay: {
    label: "모양을 기억해요",
    compliance: 0.0012,
    drag: 13,
    stretch: 1.9,
    plastic: 1.8,
    roughness: 0.35,
    transmission: 0.08,
  },
  stretch: {
    label: "쭈욱 늘어나는",
    compliance: 0.0023,
    drag: 6.5,
    stretch: 2.6,
    roughness: 0.2,
    transmission: 0.45,
  },
  bounce: {
    label: "통통 튀는 탄력",
    compliance: 0.000045,
    drag: 0.6,
    stretch: 1.5,
    bounce: 0.7,
    roughness: 0.14,
    transmission: 0.25,
  },
  wax: {
    label: "바삭한 겉 · 말랑한 속",
    compliance: 0.0006,
    drag: 5,
    stretch: 1.8,
    roughness: 0.23,
    transmission: 0.3,
  },
};
const make = (id, name, grade, color, texture, description, extra = {}) => ({
  id,
  name,
  grade,
  color,
  texture,
  description,
  shape: "round",
  ...extra,
});
export const catalog = [
  make(
    1,
    "물젤리 슬랑이",
    "C",
    "#64c8ff",
    "jelly",
    "손끝을 따라 둥글게 늘어나다, 놓으면 출렁. 가장 기본적인 촉촉함.",
    { bubbles: true },
  ),
  make(
    2,
    "우유 생크림 폼",
    "C",
    "#fff9ef",
    "foam",
    "공기를 머금은 생크림처럼 부드럽고 보송해요.",
  ),
  make(
    3,
    "폼볼 크런치 팝",
    "R",
    "#ffb6c1",
    "crunch",
    "핑크 젤리 속 작은 폼볼. 누를 때마다 오독오독.",
    { beads: "pastel" },
  ),
  make(
    4,
    "바사삭 리얼 왁뿌볼",
    "E",
    "#d81b60",
    "wax",
    "껍질을 누르고 당겨 바사삭. 분홍 코팅 아래 진한 젤리가 숨어 있어요.",
    { shell: "#f8bbd0", shellHits: 2, shellThickness: 0.065 },
  ),
  make(
    5,
    "바삭 크랙볼",
    "E",
    "#ff784d",
    "wax",
    "노란 코팅을 깨면 탱글한 오렌지 속살이 드러나요.",
    { shell: "#ffe082", shellHits: 2 },
  ),
  make(
    6,
    "쫀득 고무 찰떡",
    "R",
    "#8bc34a",
    "rubber",
    "쭉 당겼다가 놓아 보세요. 빠르고 쫀쫀하게 돌아와요.",
  ),
  make(
    7,
    "구름 숨결 스퀴시",
    "E",
    "#d995e9",
    "squishy",
    "꾸욱 누른 자국이 천천히 부풀어 오르는 느긋한 말랑이.",
  ),
  make(
    8,
    "✨우주 덩어리✨",
    "L",
    "#514084",
    "jelly",
    "깊은 보랏빛 안에 반짝이는 작은 우주.",
    { glitter: "stars" },
  ),
  make(
    9,
    "코랄 하트젤리",
    "E",
    "#ff7f6e",
    "jelly",
    "두 볼이 말랑한 코랄빛 하트. 늘어나도 마음은 그대로.",
    { shape: "heart" },
  ),
  make(
    10,
    "뭉게구름 솜슬라임",
    "E",
    "#eceae6",
    "cotton",
    "울퉁불퉁한 작은 구름을 두 손으로 모아 보세요.",
    { shape: "cloud", dust: true },
  ),
  make(
    11,
    "청량 민트젤리",
    "C",
    "#5fd7c5",
    "jelly",
    "차갑고 맑은 민트빛. 손끝에서 찰랑이는 젤리.",
  ),
  make(
    12,
    "아그작 청사과 왁뿌볼",
    "E",
    "#7cb342",
    "wax",
    "청사과색 코팅을 아그작. 작은 꼭지까지 달려 있어요.",
    { shell: "#d7ec9a", shellHits: 2, stem: true },
  ),
  make(
    13,
    "멜론 푸딩젤리",
    "R",
    "#58d668",
    "jelly",
    "말갛게 빛나는 멜론 푸딩의 탱글한 흔들림.",
  ),
  make(
    14,
    "유리알 리퀴드",
    "R",
    "#4fc3f7",
    "liquid",
    "빛이 통과하는 맑은 속살과 느슨하게 흐르는 감촉.",
    { bubbles: true },
  ),
  make(
    15,
    "포도알 톡톡",
    "R",
    "#8e44ad",
    "rubber",
    "포도알처럼 통통, 작게 눌러도 톡 하고 돌아와요.",
  ),
  make(
    16,
    "황금 꿀 슬라임",
    "E",
    "#e2b93b",
    "liquid",
    "꾸덕하고 투명한 황금 꿀이 손끝을 따라 늘어나요.",
  ),
  make(
    17,
    "몽실몽실 목화솜",
    "E",
    "#c9c4d4",
    "cotton",
    "포슬포슬한 솜 덩어리. 조금씩 주무른 모양을 기억해요.",
    { shape: "cloud", plastic: 1.1, dust: true },
  ),
  make(
    18,
    "🌈오로라 젤리🌈",
    "L",
    "#b388ff",
    "liquid",
    "만질수록 색이 흐르는, 손안의 작은 오로라.",
    { iridescent: true },
  ),
  make(
    19,
    "투명 해파리 말랑이",
    "E",
    "#dfeef2",
    "jelly",
    "투명한 해파리를 만지면 뽀얘져요. 작은 다리도 같이 흔들려요.",
    { shape: "jellyfish", jellyfish: true, face: true },
  ),
  make(
    20,
    "딸기우유 폼",
    "C",
    "#ffc7d4",
    "foam",
    "달콤한 딸기우유빛, 퐁신한 거품 촉감.",
  ),
  make(
    21,
    "레몬 젤리",
    "C",
    "#ffe36e",
    "jelly",
    "햇살을 담은 레몬빛 젤리를 쭉 늘려 보세요.",
  ),
  make(
    22,
    "초코 푸딩",
    "C",
    "#8d5a3b",
    "jelly",
    "부드러운 초콜릿 푸딩처럼 묵직하게 출렁여요.",
    { opaque: true },
  ),
  make(
    23,
    "소다 젤리",
    "C",
    "#a5dcf5",
    "jelly",
    "맑은 소다빛에 작은 기포가 떠 있어요.",
    { bubbles: true },
  ),
  make(
    24,
    "슈퍼 탱탱볼",
    "R",
    "#ff6b6b",
    "bounce",
    "위로 들어 놓아 보세요. 가장 단단하고 통통 튀어요.",
  ),
  make(
    25,
    "꾸덕 카라멜",
    "R",
    "#c98a3d",
    "clay",
    "주무른 모양이 남는 꾸덕한 카라멜.",
  ),
  make(
    26,
    "사이다 버블 팝",
    "R",
    "#bfe6f7",
    "crunch",
    "사이다색 젤리와 바삭하게 터지는 푸른 비즈.",
    { beads: "ice", fizz: true },
  ),
  make(
    27,
    "쭈욱 치즈 스트레치",
    "R",
    "#f7c948",
    "stretch",
    "고소한 치즈처럼 길고 부드럽게 늘어나요.",
  ),
  make(
    28,
    "말랑 식빵 반죽",
    "C",
    "#eddcbc",
    "squishy",
    "발효 중인 식빵 반죽처럼 천천히 되돌아와요.",
  ),
  make(
    29,
    "말차 모찌 반죽",
    "R",
    "#9dbf7d",
    "squishy",
    "쫀득하고 느린 말차색 모찌.",
  ),
  make(
    30,
    "밤하늘 별 반죽",
    "E",
    "#3a4680",
    "squishy",
    "느릿한 반죽 위에 내려앉은 별 조각들.",
    { beads: "stars" },
  ),
  make(
    31,
    "밀가루 반죽 도우",
    "C",
    "#efe3cf",
    "clay",
    "만든 모양을 간직하는 반죽. 주무르면 가루가 살짝 날려요.",
    { dust: true },
  ),
  make(
    32,
    "네온 점토",
    "R",
    "#8ef23c",
    "clay",
    "쨍한 네온빛 점토로 나만의 모양을 빚어 보세요.",
  ),
  make(
    33,
    "자석 리퀴드 퍼티",
    "E",
    "#55535f",
    "clay",
    "손끝 가까이 끌려오는 자성 퍼티. 늘어난 모양을 기억해요.",
    { magnet: true, metal: true },
  ),
  make(
    34,
    "설탕 코팅 딸기볼",
    "C",
    "#ff5f7e",
    "wax",
    "얇은 설탕 껍질은 한 번에 사르르. 속에는 작은 씨앗.",
    { shell: "#ffe3ec", shellHits: 1, shellThickness: 0.035, beads: "seeds" },
  ),
  make(
    35,
    "두툼 초코 코팅볼",
    "R",
    "#f6e7c8",
    "wax",
    "세 번 톡톡. 두꺼운 초코 껍질 아래 꾸덕한 크림.",
    {
      shell: "#6b4a2f",
      shellHits: 3,
      shellThickness: 0.11,
      plastic: 1.3,
      beads: "choco",
    },
  ),
  make(
    36,
    "쨍그랑 아이스볼",
    "E",
    "#4fb6e8",
    "wax",
    "얇은 얼음이 잘게 깨지고 청량한 기포가 올라와요.",
    {
      shell: "#d9f1fc",
      shellHits: 1,
      shellThickness: 0.035,
      chipSize: 0.7,
      fizz: true,
    },
  ),
  make(
    37,
    "✨미지의 황금 오브✨",
    "L",
    "#e9afce",
    "wax",
    "단단한 금빛 껍질 속, 열어야 알 수 있는 젤리 색.",
    {
      shell: "#e8c04a",
      shellHits: 3,
      shellThickness: 0.09,
      mystery: true,
      glitter: "gold",
    },
  ),
  make(
    38,
    "행운의 클로버 젤리",
    "E",
    "#54b45e",
    "jelly",
    "네 잎을 하나씩 당겨 보세요. 둥글게 이어진 초록 행운.",
    { shape: "clover" },
  ),
  make(
    39,
    "뽀짝 생쥐젤리",
    "E",
    "#c3c8d4",
    "jelly",
    "동그란 두 귀가 귀여운 작은 생쥐.",
    { shape: "mouse", face: true },
  ),
  make(
    40,
    "탁! 크렘브륄레",
    "R",
    "#f2e3ae",
    "wax",
    "카라멜 판을 탁! 얇은 코팅 아래 노란 커스터드.",
    { shell: "#a86a24", shellHits: 1, shellThickness: 0.045, chipSize: 1.4 },
  ),
  make(
    41,
    "콜라 톡톡젤리",
    "C",
    "#5a3722",
    "liquid",
    "짙은 콜라 속 탄산이 톡톡 터져요.",
    { fizz: true, bubbles: true },
  ),
  make(
    42,
    "몽글 비눗방울 구슬",
    "E",
    "#cfe6f4",
    "liquid",
    "큰 비눗방울이 몽글몽글. 빛에 따라 무지갯빛으로.",
    { fizz: true, bigBubbles: true, iridescent: true },
  ),
  make(
    43,
    "무지개 요정가루 젤리",
    "E",
    "#e9dcff",
    "jelly",
    "파스텔 젤리 안에서 무지개 가루가 반짝여요.",
    { glitter: "rainbow" },
  ),
  make(
    44,
    "수은 홀로 메탈",
    "E",
    "#c3cbd8",
    "clay",
    "빛나는 금속 감촉. 홀로그램 빛과 형태 기억.",
    { metal: true, iridescent: true, glitter: "silver" },
  ),
  make(
    45,
    "별사탕 컨페티 팝",
    "R",
    "#fff3f6",
    "crunch",
    "별과 하트 사탕이 알록달록 섞여 있어요.",
    { beads: "confetti" },
  ),
  make(
    46,
    "타피오카 밀크티",
    "R",
    "#e8d3b8",
    "jelly",
    "밀크티 속 까만 타피오카 펄을 콕콕.",
    { beads: "tapioca" },
  ),
  make(
    47,
    "스마일 찹쌀떡",
    "C",
    "#f5ede3",
    "squishy",
    "꾸욱 눌러도 웃고 있는 보송한 찹쌀떡.",
    { face: true },
  ),
  make(
    48,
    "쭈-욱 끈끈이 몬스터",
    "R",
    "#6fd44e",
    "stretch",
    "가장 길게 늘어나는 끈끈한 초록 친구.",
    { face: true },
  ),
  make(
    49,
    "프리즘 보석 젤리",
    "E",
    "#7fd8e8",
    "rubber",
    "일곱 빛을 반사하는 보석. 감촉은 말랑해요.",
    { shape: "gem", iridescent: true },
  ),
];
export function materialProfile(item) {
  return {
    ...textures[item.texture],
    ...(item.plastic ? { plastic: item.plastic } : {}),
    ...(item.opaque ? { transmission: 0.05 } : {}),
  };
}
export const supplies = [
  {
    id: "pearl",
    name: "진주 비즈",
    color: "#f4e7ef",
    price: 25,
    apply: { beads: "pearl" },
  },
  {
    id: "stars",
    name: "별사탕 비즈",
    color: "#efc865",
    price: 25,
    apply: { beads: "confetti" },
  },
  {
    id: "glitter",
    name: "무지개 가루",
    color: "#b6a7d9",
    price: 35,
    apply: { glitter: "rainbow" },
  },
  {
    id: "bubble",
    name: "톡톡 기포",
    color: "#9ccfd6",
    price: 25,
    apply: { fizz: true, bubbles: true },
  },
  {
    id: "wax",
    name: "딸기 왁스",
    color: "#efacc2",
    price: 40,
    apply: { shell: "#efacc2", shellHits: 1, shellThickness: 0.05 },
  },
  {
    id: "goldwax",
    name: "두꺼운 골드 왁스",
    color: "#d4b36a",
    price: 50,
    apply: { shell: "#d4b36a", shellHits: 3, shellThickness: 0.1 },
  },
  {
    id: "face",
    name: "방긋 얼굴",
    color: "#f1dac0",
    price: 20,
    apply: { face: true },
  },
];
